### ISSUE TITLE
IllegalAccessError in org.apache.commons.lang3.Strings in Gradle plugin 13.0.0

### ISSUE THREAD

**Issue by OrangeDog** [dependency-check/DependencyCheck#8714]
**Precondition**
- [x] I checked the issues list for existing open or closed reports of the same problem.

**Describe the bug**
```
An unexpected error occurred during analysis of 'C:\Users\me\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\2.3.21\6acc55c52691ce3fd41b20a0472f3513106521a5\kotlin-reflect-2.3.21.jar' (CPE Analyzer): class org.apache.commons.lang3.Strings tried to access method 'boolean org.apache.commons.lang3.CharSequenceUtils.regionMatches(java.lang.CharSequence, boolean, int, java.lang.CharSequence, int, int)' (org.apache.commons.lang3.Strings is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @6beab719; org.apache.commons.lang3.CharSequenceUtils is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @3fd155ce)

java.lang.IllegalAccessError: class org.apache.commons.lang3.Strings tried to access method 'boolean org.apache.commons.lang3.CharSequenceUtils.regionMatches(java.lang.CharSequence, boolean, int, java.lang.CharSequence, int, int)' (org.apache.commons.lang3.Strings is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @6beab719; org.apache.commons.lang3.CharSequenceUtils is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader$InstrumentingVisitableURLClassLoader @3fd155ce)
	at org.apache.commons.lang3.Strings.startsWith(Strings.java:1411)
	at org.owasp.dependencycheck.xml.suppression.SuppressionRule.cpe22UriPrefixMatches(SuppressionRule.java:731)
	at org.owasp.dependencycheck.xml.suppression.SuppressionRule.identifierMatches(SuppressionRule.java:719)
	at org.owasp.dependencycheck.xml.suppression.SuppressionRule.process(SuppressionRule.java:585)
	at org.owasp.dependencycheck.analyzer.AbstractSuppressionAnalyzer.analyzeDependency(AbstractSuppressionAnalyzer.java:121)
	at org.owasp.dependencycheck.analyzer.CpeSuppressionAnalyzer.analyzeDependency(CpeSuppressionAnalyzer.java:91)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineIdentifiers(CPEAnalyzer.java:944)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.determineCPE(CPEAnalyzer.java:285)
	at org.owasp.dependencycheck.analyzer.CPEAnalyzer.analyzeDependency(CPEAnalyzer.java:766)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:131)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Version of dependency-check used**
The problem occurs using version 13.0.0 of the gradle plugin.

**Log file**
https://gist.github.com/OrangeDog/b249007bc31d326e4a42738156586602

**To Reproduce**
Ran `:app:dependencyCheckAnalyze` on an Android project.
```groovy
dependencyCheck {
    analyzers.assemblyEnabled = false
    failBuildOnCVSS = 5.0
    format = 'XML'
    nvd.datafeedUrl = 'https://dependency-check.github.io/DependencyCheck_Builder/nvd_cache/nvdcve-{0}.json.gz'
    scanConfigurations.addAll('releaseRuntimeClasspath')
    suppressionFile = 'suppressions.xml'
}
```

**Expected behavior**
No Java errors.

**Additional context**
Worked correctly with 12.2.2.
Run with Gradle 9.6.1 on OpenJDK (Temurin) 21.0.6

**Comment by chadlwilson** [comment]
Usually caused by other plugins with clashing dependencies. Check the docs and readme on the gradle plugin. You'll need to dependency manage the version if it clashes with others on your buildSrc or plugin classpath and you need to use a lower version for compatibility with some other plugin.

e.g https://github.com/dependency-check/dependency-check-gradle#gradle-build-environment-conflicts

**Comment by OrangeDog** [comment]
That says `NoSuchMethodError`, not `IllegalAccessError`, but I'll have a look.

**Comment by chadlwilson** [comment]
Quite likely still the same problem -  ODC byte code is probably bound/dynamic dispatch to a message signature overload which is somehow private (or package) visibility on whichever version your classpath has selected. Since we target Java 11 to compile it will bind to different overloads than a native java 21 compile in some cases, leading to runtime incompatibility.

Commons lang is notorious for these kind of problems unfortunately because of the changes they do to add new overloads or change them to public which can technically break bytecode API compatibility.

If you can't figure it out please reopen an issue on the gradle plugin specifically with a minimal project to reproduce it reliably. If there is no workaround with a common version we'll have to downgrade I guess, or override the version specifically for the Gradle plugin it do something with the compile target if something has gone wrong.

**Comment by OrangeDog** [comment]
There doesn't appear to have been a dependency change, so I'm not sure what kind of constraints/overrides would help.

```
+--- org.owasp.dependencycheck:org.owasp.dependencycheck.gradle.plugin:12.2.2
|    \--- org.owasp:dependency-check-gradle:12.2.2
|         +--- org.owasp:dependency-check-core:12.2.2
...
|         |    +--- org.owasp:dependency-check-utils:12.2.2
|         |    |    +--- commons-io:commons-io:2.22.0
|         |    |    +--- org.apache.commons:commons-lang3:3.20.0
...
|         |    +--- org.apache.commons:commons-compress:1.27.1
|         |    |    +--- commons-codec:commons-codec:1.17.1
|         |    |    +--- commons-io:commons-io:2.16.1 -> 2.22.0
|         |    |    \--- org.apache.commons:commons-lang3:3.16.0 -> 3.20.0
|         |    +--- commons-io:commons-io:2.22.0
|         |    +--- org.apache.commons:commons-lang3:3.20.0
|         |    +--- org.apache.commons:commons-text:1.15.0
|         |    |    \--- org.apache.commons:commons-lang3:3.20.0
```
```
+--- org.owasp.dependencycheck:org.owasp.dependencycheck.gradle.plugin:13.0.0
|    \--- org.owasp:dependency-check-gradle:13.0.0
|         +--- org.owasp:dependency-check-core:13.0.0
...
|         |    +--- org.owasp:dependency-check-utils:13.0.0
|         |    |    +--- commons-io:commons-io:2.22.0
|         |    |    +--- org.apache.commons:commons-lang3:3.20.0
...
|         |    +--- org.apache.commons:commons-compress:1.27.1
|         |    |    +--- commons-codec:commons-codec:1.17.1
|         |    |    +--- commons-io:commons-io:2.16.1 -> 2.22.0
|         |    |    \--- org.apache.commons:commons-lang3:3.16.0 -> 3.20.0
|         |    +--- commons-io:commons-io:2.22.0
|         |    +--- org.apache.commons:commons-lang3:3.20.0
|         |    +--- org.apache.commons:commons-text:1.15.0
|         |    |    \--- org.apache.commons:commons-lang3:3.20.0
```

The only appearances of `commons-lang3` are under `org.owasp.dependencycheck.gradle.plugin`

**Comment by chadlwilson** [comment]
There is a change in the **use** of the commons lang dependency in 13.0.0 so it doesn’t necessarily have to be a change in version to expose an issue which was there before with the given library version (once given byte code is used).

Do you have a reproducer?

**Comment by chadlwilson** [comment]
IIRC Gradle itself uses commons-lang3 unshaded, but I use 9.6.1 and don’t have this problem (albeit not a kotlin project), and the integration tests are run against 9.6.1 (where loading suppressions is pretty basic logic so should be covered) so must be something more complex going on.

The error says that Strings is coming from a different classloader to CharSequenceUtils which implies 2 copies, and possibly a copy in a parent classloader that is < 3.18.0 so didn’t have the Strings class at all. ODC loads that from 3.20.0 and now cannot interoperate with CharSequenceUtils since loaded by different classloader and package private (which IIRC does not allow access across classloaders either). Kind of implies that CharSequenceUtils is being used before ODC by something earlier in Gradle logic and so is already loaded before the plugin runs.

Do you perhaps have commons-lang3 coming via buildSrc, not just plugin build environment? If you want to brute force it, try adding commons-lang3 version 3.20.0 as a dependency to buildsrc, and see if the error goes away, or via something like

```groovy
buildscript {
    dependencies {
        classpath "org.apache.commons:commons-lang3:3.20.0"
    }
}
```

**Comment by OrangeDog** [comment]
Yes, I had to add that to the root buildscript.

It didn't work in the app buildscript even though that's where the plugin is imported and the task defined and `:app:buildenvironment` tells you it's definitely using 3.20.0... (Gradle sucks).

The conflict was apparently with 3.16.0 via `com.android.tools.build:gradle:9.1.1`.

**Comment by chadlwilson** [comment]
To be fair, ODC also "sucks" a bit here. If it wasn't so painful to do so, the plugin should be using workers with isolated classpaths, or shading dependencies, or otherwise reducing the dependency tree.

Could just remove this particular use of `Strings` that manifested the conflict, but if it's not one thing it's another later on.

I'd like to get rid of commons-lang, but similar to Gradle's own usage we depend on it via commons-compress and commons-text anyway, so it seems a little futile.
